service: http-task-manager

provider:
  name: aws
  runtime: nodejs6.10
  cfLogs: true
  versionLambda: false
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
        - lambda:*
      Resource: '*'
  environment:
    TASKS_TABLE:
      Ref: Tasks
    TASK_RESULTS_TABLE:
      Ref: TaskResults
functions:
  add:
    handler: handlers/add.handler
    events:
      - http:
          method: POST
          path: add
          integration: lambda
          request:
            template:
              application/json: '$input.body'
  get:
    handler: handlers/get.handler
    events:
      - http:
          method: GET
          path: get/{id}
          integration: lambda
          request:
            template:
              application/json: '{"id": "$input.params(''id'')"}'
  update:
    handler: handlers/update.handler

resources:
  Resources:
    Tasks:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-${opt:stage}-tasks
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        StreamSpecification:
          StreamViewType: NEW_IMAGE
    TaskResults:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-${opt:stage}-task-results
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        StreamSpecification:
          StreamViewType: NEW_IMAGE